// <auto-generated />
using System;
using BikeRoubada.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace BikeRoubada.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220144117_Add-destaque")]
    partial class Adddestaque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BikeRoubada.Business.Models.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BicicletaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdBicicleta")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdTipoAlerta")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUsuarioGerador")
                        .HasColumnType("char(36)");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("point");

                    b.Property<Guid?>("UsuarioGeradorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BicicletaId");

                    b.HasIndex("IdTipoAlerta");

                    b.HasIndex("UsuarioGeradorId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Arquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("IdBicicleta")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdRoubo")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBicicleta");

                    b.HasIndex("IdRoubo");

                    b.ToTable("Arquivos", (string)null);
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Bicicleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Detalhes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdEndereco")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<Point>("LocalizacaoCadastro")
                        .IsRequired()
                        .HasColumnType("point");

                    b.Property<string>("Serial")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEndereco");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Bicicletas", (string)null);
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Roubo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRecuperacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRoubo")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdBicicleta")
                        .HasColumnType("char(36)");

                    b.Property<Point>("Localizacao")
                        .IsRequired()
                        .HasColumnType("point");

                    b.Property<string>("NumeroBoletim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdBicicleta");

                    b.ToTable("Roubos", (string)null);
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.TipoAlerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TiposAlertas");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IdentificadorPessoal")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Alerta", b =>
                {
                    b.HasOne("BikeRoubada.Business.Models.Bicicleta", "Bicicleta")
                        .WithMany()
                        .HasForeignKey("BicicletaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BikeRoubada.Business.Models.TipoAlerta", "TipoAlerta")
                        .WithMany("Alertas")
                        .HasForeignKey("IdTipoAlerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRoubada.Business.Models.Usuario", "UsuarioGerador")
                        .WithMany()
                        .HasForeignKey("UsuarioGeradorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bicicleta");

                    b.Navigation("TipoAlerta");

                    b.Navigation("UsuarioGerador");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Arquivo", b =>
                {
                    b.HasOne("BikeRoubada.Business.Models.Bicicleta", "Bicicleta")
                        .WithMany("Arquivos")
                        .HasForeignKey("IdBicicleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRoubada.Business.Models.Roubo", "Roubo")
                        .WithMany("Arquivos")
                        .HasForeignKey("IdRoubo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bicicleta");

                    b.Navigation("Roubo");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Bicicleta", b =>
                {
                    b.HasOne("BikeRoubada.Business.Models.Endereco", "Endereco")
                        .WithMany("Bicicletas")
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRoubada.Business.Models.Usuario", "Usuario")
                        .WithMany("Bicicletas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Endereco", b =>
                {
                    b.HasOne("BikeRoubada.Business.Models.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Roubo", b =>
                {
                    b.HasOne("BikeRoubada.Business.Models.Bicicleta", "Bicicleta")
                        .WithMany("Roubos")
                        .HasForeignKey("IdBicicleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bicicleta");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Bicicleta", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Roubos");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Endereco", b =>
                {
                    b.Navigation("Bicicletas");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Roubo", b =>
                {
                    b.Navigation("Arquivos");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.TipoAlerta", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("BikeRoubada.Business.Models.Usuario", b =>
                {
                    b.Navigation("Bicicletas");

                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
